// Official squad players: "NAME ON SHIRT" -> team
const officialSquadPlayers = {
  // Algeria
  'MASTIL': 'Algeria',
  'MANDI': 'Algeria',
  'ABADA': 'Algeria',
  'TOUGAI': 'Algeria',
  'BELAID': 'Algeria',
  'ZERROUKI': 'Algeria',
  'MAHREZ': 'Algeria',
  'AOUAR': 'Algeria',
  'GHOURI': 'Algeria',
  'CHAIBI': 'Algeria',
  'HADJ MOUSSA': 'Algeria',
  'BENBOUALI': 'Algeria',
  'HADJAM': 'Algeria',
  'BOUDAOUI': 'Algeria',
  'AIT NOURI': 'Algeria',
  'BENBOT': 'Algeria',
  'BELGHALI': 'Algeria',
  'AMOURA': 'Algeria',
  'BENTALEB': 'Algeria',
  'BOULBINA': 'Algeria',
  'BENSEBAINI': 'Algeria',
  'MAZA': 'Algeria',
  'ZIDANE': 'Algeria',
  'TITRAOUI': 'Algeria',
  'GHEDJEMIS': 'Algeria',
  'CHERGUI': 'Algeria',
  // Argentina
  'MUSSO': 'Argentina',
  'BALERDI': 'Argentina',
  'TAGLIAFICO': 'Argentina',
  'MONTIEL': 'Argentina',
  'PAREDES': 'Argentina',
  'MARTÍNEZ': 'Argentina',
  'DE PAUL': 'Argentina',
  'BARCO': 'Argentina',
  'J. ALVAREZ': 'Argentina',
  'MESSI': 'Argentina',
  'LO CELSO': 'Argentina',
  'RULLI': 'Argentina',
  'ROMERO': 'Argentina',
  'PALACIOS': 'Argentina',
  'N. GONZÁLEZ': 'Argentina',
  'ALMADA': 'Argentina',
  'SIMEONE': 'Argentina',
  'NICO PAZ': 'Argentina',
  'OTAMENDI': 'Argentina',
  'MAC ALLISTER': 'Argentina',
  'LOPEZ': 'Argentina',
  'L. MARTÍNEZ': 'Argentina',
  'E. MARTÍNEZ': 'Argentina',
  'E. FERNÁNDEZ': 'Argentina',
  'MEDINA': 'Argentina',
  'MOLINA': 'Argentina',
  // Australia
  'RYAN': 'Australia',
  'DEGENEK': 'Australia',
  'CIRCATI': 'Australia',
  'ITALIANO': 'Australia',
  'BOS': 'Australia',
  'GERIA': 'Australia',
  'LECKIE': 'Australia',
  'METCALFE': 'Australia',
  'TOURE': 'Australia',
  'HRUSTIC': 'Australia',
  'MABIL': 'Australia',
  'IZZO': 'Australia',
  'O'NEILL': 'Australia',
  'DEVLIN': 'Australia',
  'TREWIN': 'Australia',
  'BEHICH': 'Australia',
  'IRANKUNDA': 'Australia',
  'BEACH': 'Australia',
  'SOUTTAR': 'Australia',
  'VOLPATO': 'Australia',
  'BURGESS': 'Australia',
  'IRVINE': 'Australia',
  'VELUPILLAY': 'Australia',
  'OKON-ENGSTLER': 'Australia',
  'HERRINGTON': 'Australia',
  'YENGI': 'Australia',
  // Austria
  'SCHLAGER': 'Austria',
  'AFFENGRUBER': 'Austria',
  'DANSO': 'Austria',
  'XAVER': 'Austria',
  'POSCH': 'Austria',
  'SEIWALD': 'Austria',
  'ARNAUTOVIC': 'Austria',
  'ALABA': 'Austria',
  'SABITZER': 'Austria',
  'GRILLITSCH': 'Austria',
  'GREGORITSCH': 'Austria',
  'WIEGELE': 'Austria',
  'PENTZ': 'Austria',
  'KALAJDZIC': 'Austria',
  'LIENHART': 'Austria',
  'MWENE': 'Austria',
  'CHUKWUEMEKA': 'Austria',
  'SCHMID': 'Austria',
  'BAUMGARTNER': 'Austria',
  'LAIMER': 'Austria',
  'WIMMER': 'Austria',
  'PRASS': 'Austria',
  'FRIEDL': 'Austria',
  'WANNER': 'Austria',
  'SVOBODA': 'Austria',
  'SCHÖPF': 'Austria',
  // Belgium
  'COURTOIS': 'Belgium',
  'DEBAST': 'Belgium',
  'THIATE': 'Belgium',
  'MECHELE': 'Belgium',
  'DE CUYPER': 'Belgium',
  'WITSEL': 'Belgium',
  'DE BRUYNE': 'Belgium',
  'TIELEMANS': 'Belgium',
  'LUKAKU': 'Belgium',
  'TROSSARD': 'Belgium',
  'DOKU': 'Belgium',
  'LAMMENS': 'Belgium',
  'PENDERS': 'Belgium',
  'LUKEBAKIO': 'Belgium',
  'MEUNIER': 'Belgium',
  'DE WINTER': 'Belgium',
  'DE KETELAERE': 'Belgium',
  'SEYS': 'Belgium',
  'MOREIRA': 'Belgium',
  'VANAKEN': 'Belgium',
  'CASTAGNE': 'Belgium',
  'SAELEMAEKERS': 'Belgium',
  'RASKIN': 'Belgium',
  'ONANA': 'Belgium',
  'NGOY': 'Belgium',
  'FERNANDEZ-PARDO': 'Belgium',
  // Bosnia and Herzegovina
  'VASILJ': 'Bosnia and Herzegovina',
  'MUJAKIC': 'Bosnia and Herzegovina',
  'HADZIKADUNIC': 'Bosnia and Herzegovina',
  'MUHAREMOVIC': 'Bosnia and Herzegovina',
  'KOLASINAC': 'Bosnia and Herzegovina',
  'TAHIROVIC': 'Bosnia and Herzegovina',
  'DEDIC': 'Bosnia and Herzegovina',
  'GIGOVIC': 'Bosnia and Herzegovina',
  'BAZDAR': 'Bosnia and Herzegovina',
  'DEMIROVIC': 'Bosnia and Herzegovina',
  'DZEKO': 'Bosnia and Herzegovina',
  'JURKAS': 'Bosnia and Herzegovina',
  'BASIC': 'Bosnia and Herzegovina',
  'SUNJIC': 'Bosnia and Herzegovina',
  'MEMIC': 'Bosnia and Herzegovina',
  'HADZIAHMETOVIC': 'Bosnia and Herzegovina',
  'BURNIC': 'Bosnia and Herzegovina',
  'KATIC': 'Bosnia and Herzegovina',
  'ALAJBEGOVIC': 'Bosnia and Herzegovina',
  'BAJRAKTAREVIC': 'Bosnia and Herzegovina',
  'RADELJIC': 'Bosnia and Herzegovina',
  'ZLOMISLIC': 'Bosnia and Herzegovina',
  'TABAKOVIC': 'Bosnia and Herzegovina',
  'CELIK': 'Bosnia and Herzegovina',
  'LUKIC': 'Bosnia and Herzegovina',
  'MAHMIC': 'Bosnia and Herzegovina',
  // Brazil
  'A. BECKER': 'Brazil',
  'WESLEY': 'Brazil',
  'GABRIEL': 'Brazil',
  'MARQUINHOS': 'Brazil',
  'CASEMIRO': 'Brazil',
  'ALEX SANDRO': 'Brazil',
  'VINI JR.': 'Brazil',
  'BRUNO G.': 'Brazil',
  'CUNHA': 'Brazil',
  'NEYMAR JR': 'Brazil',
  'RAPHINHA': 'Brazil',
  'WEVERTON': 'Brazil',
  'DANILO': 'Brazil',
  'BREMER': 'Brazil',
  'LEO PEREIRA': 'Brazil',
  'DOUGLAS SANTOS': 'Brazil',
  'FABINHO': 'Brazil',
  'DANILO S.': 'Brazil',
  'ENDRICK': 'Brazil',
  'L. PAQUETA': 'Brazil',
  'L. HENRIQUE': 'Brazil',
  'MARTINELLI': 'Brazil',
  'EDERSON': 'Brazil',
  'IBANEZ': 'Brazil',
  'THIAGO': 'Brazil',
  'RAYAN': 'Brazil',
  // Canada
  'ST. CLAIR': 'Canada',
  'JOHNSTON': 'Canada',
  'JONES': 'Canada',
  'DE FOUGEROLLES': 'Canada',
  'WATERMAN': 'Canada',
  'CHOINIÈRE': 'Canada',
  'EUSTAQUIO': 'Canada',
  'KONÉ': 'Canada',
  'LARIN': 'Canada',
  'J. DAVID': 'Canada',
  'MILLAR': 'Canada',
  'OLUWASEYI': 'Canada',
  'CORNELIUS': 'Canada',
  'SHAFFELBURG': 'Canada',
  'BOMBITO': 'Canada',
  'CREPEAU': 'Canada',
  'BUCHANAN': 'Canada',
  'GOODMAN': 'Canada',
  'DAVIES': 'Canada',
  'AHMED': 'Canada',
  'OSORIO': 'Canada',
  'LARYEA': 'Canada',
  'SIGUR': 'Canada',
  'PROMISE': 'Canada',
  'SALIBA': 'Canada',
  'MARCELO': 'Canada',
  // Cape Verde
  'VOZINHA': 'Cape Verde',
  'STOPIRA': 'Cape Verde',
  'BORGES': 'Cape Verde',
  'LOPES': 'Cape Verde',
  'LOGAN': 'Cape Verde',
  'KEVIN L.': 'Cape Verde',
  'JOVANE': 'Cape Verde',
  'JOAO PAULO': 'Cape Verde',
  'BENCHIMOL': 'Cape Verde',
  'MONTEIRO': 'Cape Verde',
  'RODRIGUES': 'Cape Verde',
  'MARCIO': 'Cape Verde',
  'LOPES CABRAL': 'Cape Verde',
  'D. DUARTE': 'Cape Verde',
  'DUARTE': 'Cape Verde',
  'Y. SEMEDO': 'Cape Verde',
  'SEMEDO': 'Cape Verde',
  'ARCANJO': 'Cape Verde',
  'LIVRAMENTO': 'Cape Verde',
  'RYAN': 'Cape Verde',
  'DA COSTA': 'Cape Verde',
  'MOREIRA': 'Cape Verde',
  'DOS SANTOS': 'Cape Verde',
  'WAGNER P.': 'Cape Verde',
  'KELVIN': 'Cape Verde',
  'HÉLIO': 'Cape Verde',
  // Colombia
  'OSPINA': 'Colombia',
  'D. MUÑOZ': 'Colombia',
  'J. LUCUMI': 'Colombia',
  'ARIAS': 'Colombia',
  'K. CASTAÑO': 'Colombia',
  'RICHARD RIOS': 'Colombia',
  'LUIS DIAZ': 'Colombia',
  'CARRASCAL': 'Colombia',
  'CORDOBA': 'Colombia',
  'JAMES': 'Colombia',
  'J. ARIAS': 'Colombia',
  'C. VARGAS': 'Colombia',
  'Y. MINA': 'Colombia',
  'PUERTA': 'Colombia',
  'PORTILLA': 'Colombia',
  'J. LERMA': 'Colombia',
  'J. MOJICA': 'Colombia',
  'W. DITTA': 'Colombia',
  'C. HERNANDEZ': 'Colombia',
  'QUINTERO': 'Colombia',
  'CAMPAZ': 'Colombia',
  'MACHADO': 'Colombia',
  'SANCHEZ': 'Colombia',
  'MONTERO': 'Colombia',
  'SUAREZ': 'Colombia',
  'A. GOMEZ': 'Colombia',
  // Croatia
  'LIVAKOVIC': 'Croatia',
  'STANISIC': 'Croatia',
  'PONGRACIC': 'Croatia',
  'GVARDIOL': 'Croatia',
  'CALETA-CAR': 'Croatia',
  'SUTALO': 'Croatia',
  'MORO': 'Croatia',
  'KOVACIC': 'Croatia',
  'KRAMARIC': 'Croatia',
  'MODRIC': 'Croatia',
  'BUDIMIR': 'Croatia',
  'PANDUR': 'Croatia',
  'VLASIC': 'Croatia',
  'PERISIC': 'Croatia',
  'PASALIC': 'Croatia',
  'BATURINA': 'Croatia',
  'P. SUCIC': 'Croatia',
  'JAKIC': 'Croatia',
  'FRUK': 'Croatia',
  'MATANOVIC': 'Croatia',
  'SUCIC': 'Croatia',
  'VUSKOVIC': 'Croatia',
  'KOTARSKI': 'Croatia',
  'M. PASALIC': 'Croatia',
  'ERLIC': 'Croatia',
  'MUSA': 'Croatia',
  // Curaçao
  'ROOM': 'Curaçao',
  'SAMBO': 'Curaçao',
  'GAARI': 'Curaçao',
  'VAN EIJMA': 'Curaçao',
  'FLORANUS': 'Curaçao',
  'ROEMERATOE': 'Curaçao',
  'J. BACUNA': 'Curaçao',
  'COMENENCIA': 'Curaçao',
  'LOCADIA': 'Curaçao',
  'L. BACUNA': 'Curaçao',
  'ANTONISSE': 'Curaçao',
  'HANSEN': 'Curaçao',
  'NOSLIN': 'Curaçao',
  'GORRE': 'Curaçao',
  'MARTHA': 'Curaçao',
  'MARGARITHA': 'Curaçao',
  'KUWAS': 'Curaçao',
  'OBISPO': 'Curaçao',
  'KASTANEER': 'Curaçao',
  'BRENET': 'Curaçao',
  'CHONG': 'Curaçao',
  'FELIDA': 'Curaçao',
  'BAZOER': 'Curaçao',
  'FONVILLE': 'Curaçao',
  'BODAK': 'Curaçao',
  'DOORNBUSCH': 'Curaçao',
  // Czech Republic
  'KOVAR': 'Czech Republic',
  'ZIMA': 'Czech Republic',
  'HOLES': 'Czech Republic',
  'HRANAC': 'Czech Republic',
  'COUFAL': 'Czech Republic',
  'CHALOUPEK': 'Czech Republic',
  'KREJCI': 'Czech Republic',
  'DARIDA': 'Czech Republic',
  'HLOZEK': 'Czech Republic',
  'SCHICK': 'Czech Republic',
  'KUCHTA': 'Czech Republic',
  'CERV': 'Czech Republic',
  'CHYTIL': 'Czech Republic',
  'JURASEK': 'Czech Republic',
  'SULC': 'Czech Republic',
  'STANEK': 'Czech Republic',
  'PROVOD': 'Czech Republic',
  'SADILEK': 'Czech Republic',
  'CHORY': 'Czech Republic',
  'ZELENY': 'Czech Republic',
  'DOUDERA': 'Czech Republic',
  'SOUCEK': 'Czech Republic',
  'HORNICEK': 'Czech Republic',
  'SOJKA': 'Czech Republic',
  'SOCHUREK': 'Czech Republic',
  'VISINSKY': 'Czech Republic',
  // DR Congo
  'MPASI': 'DR Congo',
  'WAN BISSAKA': 'DR Congo',
  'KAPUADI': 'DR Congo',
  'TUANZEBE': 'DR Congo',
  'BATUBINSIKA': 'DR Congo',
  'MUKAU': 'DR Congo',
  'MBUKU': 'DR Congo',
  'MOUTOUSSAMY': 'DR Congo',
  'CIPENGA': 'DR Congo',
  'BONGONDA': 'DR Congo',
  'KAKUTA': 'DR Congo',
  'J. KAYEMBE': 'DR Congo',
  'ELIA': 'DR Congo',
  'SADIKI': 'DR Congo',
  'TSHIBOLA': 'DR Congo',
  'FAYULU': 'DR Congo',
  'BAKAMBU': 'DR Congo',
  'PICKEL': 'DR Congo',
  'MAYELE': 'DR Congo',
  'WISSA': 'DR Congo',
  'EPOLO': 'DR Congo',
  'MBEMBA': 'DR Congo',
  'BANZA': 'DR Congo',
  'G. KALULU': 'DR Congo',
  'KAYEMBE': 'DR Congo',
  'MASUAKU': 'DR Congo',
  // Ecuador
  'GALINDEZ': 'Ecuador',
  'TORRES': 'Ecuador',
  'HINCAPIE': 'Ecuador',
  'ORDOÑEZ': 'Ecuador',
  'ALCIVAR': 'Ecuador',
  'PACHO': 'Ecuador',
  'ESTUPIÑAN': 'Ecuador',
  'A. VALENCIA': 'Ecuador',
  'YEBOAH ZAMORA': 'Ecuador',
  'PAEZ': 'Ecuador',
  'RODRIGUEZ': 'Ecuador',
  'RAMIREZ': 'Ecuador',
  'E. VALENCIA': 'Ecuador',
  'MINDA': 'Ecuador',
  'VITE': 'Ecuador',
  'J. CAICEDO': 'Ecuador',
  'PRECIADO': 'Ecuador',
  'CASTILLO': 'Ecuador',
  'PLATA': 'Ecuador',
  'ANGULO': 'Ecuador',
  'FRANCO': 'Ecuador',
  'VALLE': 'Ecuador',
  'M. CAICEDO': 'Ecuador',
  'AREVALO': 'Ecuador',
  'POROZO': 'Ecuador',
  'MEDINA': 'Ecuador',
  // Egypt
  'M. ELSHENAWY': 'Egypt',
  'YASSER': 'Egypt',
  'M. HANY': 'Egypt',
  'HOSSAM': 'Egypt',
  'R. RABIAA': 'Egypt',
  'M. ABDELMONEIM': 'Egypt',
  'M. TREZEGUET': 'Egypt',
  'E. ASHOUR': 'Egypt',
  'ABDELKARIM': 'Egypt',
  'M. SALAH': 'Egypt',
  'ZICO': 'Egypt',
  'H. HASSAN': 'Egypt',
  'A. FATOUH': 'Egypt',
  'H. FATHY': 'Egypt',
  'K. HAFEZ': 'Egypt',
  'M. SOLIMAN': 'Egypt',
  'M. LASHIN': 'Egypt',
  'DONGA': 'Egypt',
  'M. ATTIA': 'Egypt',
  'I. ADEL': 'Egypt',
  'M. SABER': 'Egypt',
  'MARMOUSH': 'Egypt',
  'SHOUBIR': 'Egypt',
  'T. ALAA': 'Egypt',
  'ZIZO': 'Egypt',
  'M. ALAA': 'Egypt',
  // England
  'PICKFORD': 'England',
  'KONSA': 'England',
  'O'REILLY': 'England',
  'RICE': 'England',
  'STONES': 'England',
  'GUEHI': 'England',
  'SAKA': 'England',
  'ANDERSON': 'England',
  'KANE': 'England',
  'BELLINGHAM': 'England',
  'RASHFORD': 'England',
  'LIVRAMENTO': 'England',
  'D. HENDERSON': 'England',
  'J. HENDERSON': 'England',
  'BURN': 'England',
  'MAINOO': 'England',
  'ROGERS': 'England',
  'GORDON': 'England',
  'WATKINS': 'England',
  'MADUEKE': 'England',
  'EZE': 'England',
  'TONEY': 'England',
  'TRAFFORD': 'England',
  'JAMES': 'England',
  'SPENCE': 'England',
  'QUANSAH': 'England',
  // France
  'SAMBA': 'France',
  'GUSTO': 'France',
  'DIGNE': 'France',
  'UPAMECANO': 'France',
  'KOUNDE': 'France',
  'KONE': 'France',
  'DEMBELE': 'France',
  'TCHOUAMENI': 'France',
  'THURAM': 'France',
  'MBAPPE': 'France',
  'OLISE': 'France',
  'BARCOLA': 'France',
  'KANTE': 'France',
  'RABIOT': 'France',
  'KONATE': 'France',
  'MAIGNAN': 'France',
  'SALIBA': 'France',
  'ZAIRE EMERY': 'France',
  'T. HERNANDEZ': 'France',
  'DOUE': 'France',
  'L. HERNANDEZ': 'France',
  'MATETA': 'France',
  'RISSER': 'France',
  'CHERKI': 'France',
  'AKLIOUCHE': 'France',
  'LACROIX': 'France',
  // Germany
  'NEUER': 'Germany',
  'RUDIGER': 'Germany',
  'ANTON': 'Germany',
  'TAH': 'Germany',
  'PAVLOVIC': 'Germany',
  'KIMMICH': 'Germany',
  'HAVERTZ': 'Germany',
  'GORETZKA': 'Germany',
  'LEWELING': 'Germany',
  'MUSIALA': 'Germany',
  'WOLTEMADE': 'Germany',
  'BAUMANN': 'Germany',
  'GROSS': 'Germany',
  'BEIER': 'Germany',
  'SCHLOTTERBECK': 'Germany',
  'STILLER': 'Germany',
  'WIRTZ': 'Germany',
  'BROWN': 'Germany',
  'SANÉ': 'Germany',
  'AMIRI': 'Germany',
  'NÜBEL': 'Germany',
  'RAUM': 'Germany',
  'NMECHA': 'Germany',
  'THIAW': 'Germany',
  'KARL': 'Germany',
  'UNDAV': 'Germany',
  // Ghana
  'ZIGI': 'Ghana',
  'SEIDU': 'Ghana',
  'CALEB': 'Ghana',
  'ADJETEY': 'Ghana',
  'THOMAS': 'Ghana',
  'SULEMAN': 'Ghana',
  'FATAWU': 'Ghana',
  'SIBO': 'Ghana',
  'AYEW': 'Ghana',
  'ASANTE': 'Ghana',
  'SEMENYO': 'Ghana',
  'ANANG': 'Ghana',
  'BAAH': 'Ghana',
  'MENSAH': 'Ghana',
  'OWUSU': 'Ghana',
  'ASARE': 'Ghana',
  'BABA': 'Ghana',
  'OPOKU': 'Ghana',
  'WILLIAMS': 'Ghana',
  'BOAKYE': 'Ghana',
  'PEPRAH': 'Ghana',
  'KAMALDEEN': 'Ghana',
  'LUCKASSEN': 'Ghana',
  'NUAMAH': 'Ghana',
  'ADU': 'Ghana',
  'SENEYA': 'Ghana',
  // Haiti
  'PLACIDE': 'Haiti',
  'ARCUS': 'Haiti',
  'THERMONCY': 'Haiti',
  'ADE': 'Haiti',
  'DELCROIX': 'Haiti',
  'SAINTE': 'Haiti',
  'ETIENNE JR': 'Haiti',
  'EXPERIENCE': 'Haiti',
  'NAZON': 'Haiti',
  'BELLEGARDE': 'Haiti',
  'DEEDSON': 'Haiti',
  'A. PIERRE': 'Haiti',
  'LACROIX': 'Haiti',
  'L. PIERRE': 'Haiti',
  'PROVIDENCE': 'Haiti',
  'JOSEPH': 'Haiti',
  'JEAN JACQUES': 'Haiti',
  'ISIDOR': 'Haiti',
  'FORTUNE': 'Haiti',
  'PIERROT': 'Haiti',
  'CASIMIR': 'Haiti',
  'DUVERNE': 'Haiti',
  'DUVERGER': 'Haiti',
  'PAUGIN': 'Haiti',
  'SIMON': 'Haiti',
  'W. PIERRE': 'Haiti',
  // Iran
  'BEIRANVAND': 'Iran',
  'SALEH': 'Iran',
  'E. HAJISAFI': 'Iran',
  'SHOJA': 'Iran',
  'M. MOHAMMADI': 'Iran',
  'S. EZATOLAHI': 'Iran',
  'A. JAHANBAKHSH': 'Iran',
  'M. MOHEBI': 'Iran',
  'TAREMI': 'Iran',
  'MEHDI GHAYEDI': 'Iran',
  'A. ALIPOUR': 'Iran',
  'PAYAM': 'Iran',
  'KANANI': 'Iran',
  'GHODDOOS': 'Iran',
  'ROOZBEH': 'Iran',
  'M. TORABI': 'Iran',
  'ARYA': 'Iran',
  'AMIRHOSSEIN': 'Iran',
  'ALI': 'Iran',
  'SHAHRIYAR': 'Iran',
  'MOHAMMAD': 'Iran',
  'HOSSEINI': 'Iran',
  'RAMIN': 'Iran',
  'DARGAHI': 'Iran',
  'DANIAL': 'Iran',
  'RAZAGH': 'Iran',
  // Iraq
  'FAHAD': 'Iraq',
  'REBIN': 'Iraq',
  'HUSSEIN': 'Iraq',
  'ZAID T.': 'Iraq',
  'AKAM': 'Iraq',
  'MUNAF': 'Iraq',
  'YOUSSEF': 'Iraq',
  'IBRAHIM': 'Iraq',
  'AL-HAMADI': 'Iraq',
  'MOHANAD': 'Iraq',
  'AHMED Q.': 'Iraq',
  'JALAL': 'Iraq',
  'ALI Y.': 'Iraq',
  'Z. IQBAL': 'Iraq',
  'AHMED': 'Iraq',
  'AL-AMMARI': 'Iraq',
  'ALI J.': 'Iraq',
  'AYMEN': 'Iraq',
  'K. YAKOB': 'Iraq',
  'AIMAR': 'Iraq',
  'MARKO': 'Iraq',
  'AHMED B.': 'Iraq',
  'DOSKI': 'Iraq',
  'ZAID I.': 'Iraq',
  'MUSTAFA': 'Iraq',
  'FRANS': 'Iraq',
  // Ivory Coast
  'Y. FOFANA': 'Ivory Coast',
  'O. DIOMANDE': 'Ivory Coast',
  'G. KONAN': 'Ivory Coast',
  'SERI': 'Ivory Coast',
  'SINGO': 'Ivory Coast',
  'FOFANA': 'Ivory Coast',
  'KOSSOUNOU': 'Ivory Coast',
  'KESSIE': 'Ivory Coast',
  'BONNY': 'Ivory Coast',
  'ADINGRA': 'Ivory Coast',
  'YAN DIOMANDE': 'Ivory Coast',
  'WAHI': 'Ivory Coast',
  'OPERI': 'Ivory Coast',
  'DIAKITE': 'Ivory Coast',
  'AMAD': 'Ivory Coast',
  'KONE': 'Ivory Coast',
  'G. DOUE': 'Ivory Coast',
  'SANGARE': 'Ivory Coast',
  'PEPE': 'Ivory Coast',
  'AGBADOU': 'Ivory Coast',
  'NDICKA': 'Ivory Coast',
  'GUESSAND': 'Ivory Coast',
  'LAFONT': 'Ivory Coast',
  'TOURE': 'Ivory Coast',
  'GUIAGON': 'Ivory Coast',
  'INAO': 'Ivory Coast',
  // Japan
  'SUZUKI': 'Japan',
  'SUGAWARA': 'Japan',
  'TANIGUCHI': 'Japan',
  'ITAKURA': 'Japan',
  'NAGATOMO': 'Japan',
  'ENDO': 'Japan',
  'TANAKA': 'Japan',
  'KUBO': 'Japan',
  'GOTO': 'Japan',
  'DOAN': 'Japan',
  'DAIZEN': 'Japan',
  'OSAKO': 'Japan',
  'NAKAMURA': 'Japan',
  'ITO': 'Japan',
  'KAMADA': 'Japan',
  'WATANABE': 'Japan',
  'Y. SUZUKI': 'Japan',
  'AYASE': 'Japan',
  'OGAWA': 'Japan',
  'SEKO': 'Japan',
  'H. ITO': 'Japan',
  'TOMIYASU': 'Japan',
  'HAYAKAWA': 'Japan',
  'SANO': 'Japan',
  'J. SUZUKI': 'Japan',
  'SHIOGAI': 'Japan',
  // Jordan
  'YAZEED': 'Jordan',
  'ABU HASHEESH': 'Jordan',
  'NASIB': 'Jordan',
  'ABU DHAB': 'Jordan',
  'ALARAB': 'Jordan',
  'JAMOUS': 'Jordan',
  'ABU ZRAIQ': 'Jordan',
  'ALRAWABDEH': 'Jordan',
  'OLWAN': 'Jordan',
  'ALTAMARI': 'Jordan',
  'ODEH': 'Jordan',
  'BANI ATEYAH': 'Jordan',
  'ALMARDI': 'Jordan',
  'RAJAEI': 'Jordan',
  'SADEH': 'Jordan',
  'ABULNADI': 'Jordan',
  'SALEM': 'Jordan',
  'SABRA': 'Jordan',
  'SAEED': 'Jordan',
  'ABU TAHA': 'Jordan',
  'NIZAR': 'Jordan',
  'ALFAKHORI': 'Jordan',
  'EHSAN': 'Jordan',
  'AZAIZEH': 'Jordan',
  'ALDAOUD': 'Jordan',
  'BADAWI': 'Jordan',
  // Mexico
  'R. RANGEL': 'Mexico',
  'J. SÁNCHEZ': 'Mexico',
  'C. MONTES': 'Mexico',
  'E. ÁLVAREZ': 'Mexico',
  'J. VÁSQUEZ': 'Mexico',
  'E. LIRA': 'Mexico',
  'L. ROMO': 'Mexico',
  'FIDALGO': 'Mexico',
  'RAÚL': 'Mexico',
  'A. VEGA': 'Mexico',
  'S. GIMÉNEZ': 'Mexico',
  'C. ACEVEDO': 'Mexico',
  'G. OCHOA': 'Mexico',
  'A. GONZÁLEZ': 'Mexico',
  'I. REYES': 'Mexico',
  'J. QUIÑONES': 'Mexico',
  'ORBELÍN': 'Mexico',
  'O. VARGAS': 'Mexico',
  'G. MORA': 'Mexico',
  'M. CHÁVEZ': 'Mexico',
  'C. HUERTA': 'Mexico',
  'G. MARTÍNEZ': 'Mexico',
  'J. GALLARDO': 'Mexico',
  'L. CHÁVEZ': 'Mexico',
  'R. ALVARADO': 'Mexico',
  'B. GUTIÉRREZ': 'Mexico',
  // Morocco
  'BONO': 'Morocco',
  'HAKIMI': 'Morocco',
  'MAZRAOUI': 'Morocco',
  'AMRABAT': 'Morocco',
  'AGUERD': 'Morocco',
  'BOUADDI': 'Morocco',
  'TALBI': 'Morocco',
  'OUAHI': 'Morocco',
  'RAHIMI': 'Morocco',
  'BRAHIM': 'Morocco',
  'SAIBARI': 'Morocco',
  'EL KAJOUI': 'Morocco',
  'EL OUAHDI': 'Morocco',
  'ISSA': 'Morocco',
  'EL MOURABET': 'Morocco',
  'YASSINE': 'Morocco',
  'EZZALZOULI': 'Morocco',
  'RIAD': 'Morocco',
  'BELAMMARI': 'Morocco',
  'EL KAABI': 'Morocco',
  'AMAIMOUNI': 'Morocco',
  'TAGNAOUTI': 'Morocco',
  'EL KHANNOUSS': 'Morocco',
  'EL AYNAOUI': 'Morocco',
  'HALHAL': 'Morocco',
  'SALAH-EDDINE': 'Morocco',
  // Netherlands
  'VERBRUGGEN': 'Netherlands',
  'J. TIMBER': 'Netherlands',
  'DE ROON': 'Netherlands',
  'VIRGIL': 'Netherlands',
  'AKÉ': 'Netherlands',
  'VAN HECKE': 'Netherlands',
  'KLUIVERT': 'Netherlands',
  'GRAVENBERCH': 'Netherlands',
  'WEGHORST': 'Netherlands',
  'MEMPHIS': 'Netherlands',
  'GAKPO': 'Netherlands',
  'WIEFFER': 'Netherlands',
  'ROEFS': 'Netherlands',
  'REIJNDERS': 'Netherlands',
  'VAN DE VEN': 'Netherlands',
  'TIL': 'Netherlands',
  'LANG': 'Netherlands',
  'MALEN': 'Netherlands',
  'BROBBEY': 'Netherlands',
  'KOOPMEINERS': 'Netherlands',
  'F. DE JONG': 'Netherlands',
  'DUMFRIES': 'Netherlands',
  'FLEKKEN': 'Netherlands',
  'SUMMERVILLE': 'Netherlands',
  'HATO': 'Netherlands',
  'Q. TIMBER': 'Netherlands',
  // New Zealand
  'CROCOMBE': 'New Zealand',
  'PAYNE': 'New Zealand',
  'DE VRIES': 'New Zealand',
  'BINDON': 'New Zealand',
  'BOXALL': 'New Zealand',
  'BELL': 'New Zealand',
  'GARBETT': 'New Zealand',
  'STAMENIC': 'New Zealand',
  'WOOD': 'New Zealand',
  'SINGH': 'New Zealand',
  'JUST': 'New Zealand',
  'PAULSEN': 'New Zealand',
  'CACACE': 'New Zealand',
  'RUFER': 'New Zealand',
  'PIJNAKER': 'New Zealand',
  'SURMAN': 'New Zealand',
  'BARBAROUSES': 'New Zealand',
  'WAINE': 'New Zealand',
  'OLD': 'New Zealand',
  'MCCOWATT': 'New Zealand',
  'RANDALL': 'New Zealand',
  'WOUD': 'New Zealand',
  'THOMAS': 'New Zealand',
  'ELLIOT': 'New Zealand',
  'BAYLISS': 'New Zealand',
  'SMITH': 'New Zealand',
  // Norway
  'NYLAND': 'Norway',
  'THORSBY': 'Norway',
  'VASSBAKK AJER': 'Norway',
  'ØSTIGÅRD': 'Norway',
  'MØLLER WOLFE': 'Norway',
  'BERG': 'Norway',
  'SØRLOTH': 'Norway',
  'BERGE': 'Norway',
  'BRAUT HAALAND': 'Norway',
  'ØDEGAARD': 'Norway',
  'STRAND LARSEN': 'Norway',
  'TANGVIK': 'Norway',
  'SELVIK': 'Norway',
  'AURSNES': 'Norway',
  'BJØRKAN': 'Norway',
  'HOLMGREN': 'Norway',
  'HEGGEM': 'Norway',
  'THORSTVEDT': 'Norway',
  'AASGAARD': 'Norway',
  'NUSA': 'Norway',
  'SCHJELDERUP': 'Norway',
  'BOBB': 'Norway',
  'HAUGE': 'Norway',
  'LANGÅS': 'Norway',
  'FALCHENER': 'Norway',
  'RYERSON': 'Norway',
  // Panama
  'MEJÍA': 'Panama',
  'BLACKMAN': 'Panama',
  'CORDOBA': 'Panama',
  'F. ESCOBAR': 'Panama',
  'FARIÑA': 'Panama',
  'MARTÍNEZ': 'Panama',
  'J.L. RODRÍGUEZ': 'Panama',
  'CARRASQUILLA': 'Panama',
  'T. RODRÍGUEZ': 'Panama',
  'ISMAEL': 'Panama',
  'BÁRCENAS': 'Panama',
  'SAMUDIO': 'Panama',
  'RAMOS': 'Panama',
  'HARVEY': 'Panama',
  'DAVIS': 'Panama',
  'ANDRADE': 'Panama',
  'FAJARDO': 'Panama',
  'WATERMAN': 'Panama',
  'QUINTERO': 'Panama',
  'GODOY': 'Panama',
  'YANIS': 'Panama',
  'MOSQUERA': 'Panama',
  'A. MURILLO': 'Panama',
  'LONDONO': 'Panama',
  'MILLER': 'Panama',
  'GUTIÉRREZ': 'Panama',
  // Paraguay
  'FERNANDEZ': 'Paraguay',
  'VELÁZQUEZ': 'Paraguay',
  'ALDERETE': 'Paraguay',
  'CÁCERES': 'Paraguay',
  'BALBUENA': 'Paraguay',
  'ALONSO': 'Paraguay',
  'SOSA': 'Paraguay',
  'D. GOMEZ': 'Paraguay',
  'SANABRIA': 'Paraguay',
  'M. ALMIRÓN': 'Paraguay',
  'MAURICIO': 'Paraguay',
  'O. GILL': 'Paraguay',
  'CANALE': 'Paraguay',
  'CUBAS': 'Paraguay',
  'G. GOMEZ': 'Paraguay',
  'BOBADILLA': 'Paraguay',
  'R. GAMARRA': 'Paraguay',
  'ARCE': 'Paraguay',
  'ENCISO': 'Paraguay',
  'OJEDA': 'Paraguay',
  'AVALOS': 'Paraguay',
  'OLIVEIRA': 'Paraguay',
  'GALARZA': 'Paraguay',
  'CABALLERO': 'Paraguay',
  'PITTA': 'Paraguay',
  'MAIDANA': 'Paraguay',
  // Portugal
  'DIOGO COSTA': 'Portugal',
  'N. SEMEDO': 'Portugal',
  'RÚBEN DIAS': 'Portugal',
  'TOMAS A.': 'Portugal',
  'DALOT': 'Portugal',
  'MATHEUS N.': 'Portugal',
  'RONALDO': 'Portugal',
  'B. FERNANDES': 'Portugal',
  'G. RAMOS': 'Portugal',
  'BERNARDO': 'Portugal',
  'JOÃO FÉLIX': 'Portugal',
  'JOSÉ SÁ': 'Portugal',
  'RENATO VEIGA': 'Portugal',
  'G. INÁCIO': 'Portugal',
  'JOÃO NEVES': 'Portugal',
  'TRINCÃO': 'Portugal',
  'RAFA LEÃO': 'Portugal',
  'NETO': 'Portugal',
  'G. GUEDES': 'Portugal',
  'JOÃO CANCELO': 'Portugal',
  'R. NEVES': 'Portugal',
  'RUI SILVA': 'Portugal',
  'VITINHA': 'Portugal',
  'SAMU': 'Portugal',
  'N. MENDES': 'Portugal',
  'F. CONCEIÇÃO': 'Portugal',
  // Qatar
  'ABUNADA': 'Qatar',
  'PEDRO': 'Qatar',
  'L. MENDES': 'Qatar',
  'GUEYE': 'Qatar',
  'JASSEM': 'Qatar',
  'A. AZIZ': 'Qatar',
  'ALAEDDIN': 'Qatar',
  'EDMILSON JR.': 'Qatar',
  'MUNTARI': 'Qatar',
  'ALHAYDOS': 'Qatar',
  'AFIF': 'Qatar',
  'KARIM': 'Qatar',
  'AYOUB': 'Qatar',
  'HOMAM': 'Qatar',
  'YUSUF': 'Qatar',
  'KHOUKHI': 'Qatar',
  'A. ALGANEHI': 'Qatar',
  'SULTAN': 'Qatar',
  'ALMOEZ': 'Qatar',
  'A. FATHY': 'Qatar',
  'SALAH': 'Qatar',
  'BARSHAM': 'Qatar',
  'MADIBO': 'Qatar',
  'TAHSIN': 'Qatar',
  'ALHASHMI': 'Qatar',
  'MANAI': 'Qatar',
  // Saudi Arabia
  'ALAQIDI': 'Saudi Arabia',
  'MAJRASHI': 'Saudi Arabia',
  'LAJAMI': 'Saudi Arabia',
  'ALAMRI': 'Saudi Arabia',
  'ALTAMBAKTI': 'Saudi Arabia',
  'NASSER': 'Saudi Arabia',
  'MUSAB': 'Saudi Arabia',
  'AIMAN': 'Saudi Arabia',
  'FERAS': 'Saudi Arabia',
  'SALEM': 'Saudi Arabia',
  'ALSHEHRI': 'Saudi Arabia',
  'SAUD': 'Saudi Arabia',
  'NAWAF': 'Saudi Arabia',
  'KADISH': 'Saudi Arabia',
  'ALKHAIBARI': 'Saudi Arabia',
  'ZIYAD': 'Saudi Arabia',
  'KHALID': 'Saudi Arabia',
  'ALHAJJI': 'Saudi Arabia',
  'ALHAMDDAN': 'Saudi Arabia',
  'MANDASH': 'Saudi Arabia',
  'ALOWAIS': 'Saudi Arabia',
  'ALKASSAR': 'Saudi Arabia',
  'KANNO': 'Saudi Arabia',
  'MOTEB': 'Saudi Arabia',
  'JEHAD': 'Saudi Arabia',
  'MOHAMMED': 'Saudi Arabia',
  // Scotland
  'GUNN': 'Scotland',
  'HICKEY': 'Scotland',
  'ROBERTSON': 'Scotland',
  'MCTOMINAY': 'Scotland',
  'HANLEY': 'Scotland',
  'TIERNEY': 'Scotland',
  'MCGINN': 'Scotland',
  'FLETCHER': 'Scotland',
  'DYKES': 'Scotland',
  'ADAMS': 'Scotland',
  'CHRISTIE': 'Scotland',
  'KELLY': 'Scotland',
  'HENDRY': 'Scotland',
  'STEWART': 'Scotland',
  'SOUTTAR': 'Scotland',
  'HYAM': 'Scotland',
  'GANNON DOAK': 'Scotland',
  'HIRST': 'Scotland',
  'FERGUSON': 'Scotland',
  'SHANKLAND': 'Scotland',
  'GORDON': 'Scotland',
  'PATTERSON': 'Scotland',
  'MCLEAN': 'Scotland',
  'RALSTON': 'Scotland',
  'CURTIS': 'Scotland',
  'MCKENNA': 'Scotland',
  // Senegal
  'Y. DIOUF': 'Senegal',
  'SARR': 'Senegal',
  'KOULIBALY': 'Senegal',
  'SECK': 'Senegal',
  'GANA': 'Senegal',
  'P.I. CISS': 'Senegal',
  'DIAO': 'Senegal',
  'LAMINE': 'Senegal',
  'B. DIENG': 'Senegal',
  'MANÉ': 'Senegal',
  'JACKSON': 'Senegal',
  'CHERIF': 'Senegal',
  'NDIAYE': 'Senegal',
  'JAKOBS': 'Senegal',
  'KRÉPIN': 'Senegal',
  'MENDY': 'Senegal',
  'P.M. SARR': 'Senegal',
  'SARR': 'Senegal',
  'NIAKHATE': 'Senegal',
  'MBAYE': 'Senegal',
  'H. DIARRA': 'Senegal',
  'BARA': 'Senegal',
  'DIAW': 'Senegal',
  'A. MENDY': 'Senegal',
  'DIOUF': 'Senegal',
  'GUEYE': 'Senegal',
  // South Africa
  'WILLIAMS': 'South Africa',
  'MATULUDI': 'South Africa',
  'NDAMANE': 'South Africa',
  'MOKOENA': 'South Africa',
  'MBATHA': 'South Africa',
  'MODIBA': 'South Africa',
  'APPOLLIS': 'South Africa',
  'MOREMI': 'South Africa',
  'FOSTER': 'South Africa',
  'MOFOKENG': 'South Africa',
  'ZWANE': 'South Africa',
  'MASEKO': 'South Africa',
  'SITHOLE': 'South Africa',
  'MBOKAZI': 'South Africa',
  'RAYNERS': 'South Africa',
  'CHAINE': 'South Africa',
  'MAKGOPA': 'South Africa',
  'KABINI': 'South Africa',
  'SIBISI': 'South Africa',
  'MUDAU': 'South Africa',
  'OKON': 'South Africa',
  'GOSS': 'South Africa',
  'ADAMS': 'South Africa',
  'MAKHANYA': 'South Africa',
  'SEBELEBELE': 'South Africa',
  'CROSS': 'South Africa',
  // South Korea
  'SEUNGGYU': 'South Korea',
  'HANBEOM': 'South Korea',
  'GIHYUK': 'South Korea',
  'MINJAE': 'South Korea',
  'TAEHYEON': 'South Korea',
  'INBEOM': 'South Korea',
  'HEUNGMIN': 'South Korea',
  'SEUNGHO': 'South Korea',
  'GUSEUNG': 'South Korea',
  'JAESUNG': 'South Korea',
  'HEECHAN': 'South Korea',
  'BUMKEUN': 'South Korea',
  'TAESEOK': 'South Korea',
  'WIJE': 'South Korea',
  'MOONHWAN': 'South Korea',
  'JINSEOB': 'South Korea',
  'JUNHO': 'South Korea',
  'HYEONGYU': 'South Korea',
  'KANGIN': 'South Korea',
  'HYUNJUN': 'South Korea',
  'HYEONWOO': 'South Korea',
  'YOUNGWOO': 'South Korea',
  'JENS': 'South Korea',
  'JINGYU': 'South Korea',
  'JISUNG': 'South Korea',
  'DONGGYEONG': 'South Korea',
  // Spain
  'RAYA': 'Spain',
  'MARC PUBILL': 'Spain',
  'GRIMALDO': 'Spain',
  'ERIC': 'Spain',
  'M. LLORENTE': 'Spain',
  'MERINO': 'Spain',
  'FERRAN': 'Spain',
  'FABIÁN': 'Spain',
  'GAVI': 'Spain',
  'OLMO': 'Spain',
  'JEREMY': 'Spain',
  'PEDRO PORRO': 'Spain',
  'JOAN GARCÍA': 'Spain',
  'LAPORTE': 'Spain',
  'ALEX B.': 'Spain',
  'RODRIGO': 'Spain',
  'WILLIAMS JR': 'Spain',
  'ZUBIMENDI': 'Spain',
  'LAMINE YAMAL': 'Spain',
  'PEDRI': 'Spain',
  'OYARZABAL': 'Spain',
  'CUBARSI': 'Spain',
  'UNAI SIMÓN': 'Spain',
  'CUCURELLA': 'Spain',
  'VICTOR M.V.': 'Spain',
  'B. IGLESIAS': 'Spain',
  // Sweden
  'ZETTERSTRÖM': 'Sweden',
  'LAGERBIELKE': 'Sweden',
  'LINDELÖF': 'Sweden',
  'HIEN': 'Sweden',
  'GUDMUNDSSON': 'Sweden',
  'H. JOHANSSON': 'Sweden',
  'BERGVALL': 'Sweden',
  'SVENSSON': 'Sweden',
  'ISAK': 'Sweden',
  'NYGREN': 'Sweden',
  'ELANGA': 'Sweden',
  'V. JOHANSSON': 'Sweden',
  'SEMA': 'Sweden',
  'EKDAL': 'Sweden',
  'STARFELT': 'Sweden',
  'KARLSTRÖM': 'Sweden',
  'GYÖKERES': 'Sweden',
  'AYARI': 'Sweden',
  'SVANBERG': 'Sweden',
  'SMITH': 'Sweden',
  'BERNHARDSSON': 'Sweden',
  'ZENELI': 'Sweden',
  'NORDFELDT': 'Sweden',
  'STROUD': 'Sweden',
  'NILSSON': 'Sweden',
  'ALI': 'Sweden',
  // Switzerland
  'KOBEL': 'Switzerland',
  'MUHEIM': 'Switzerland',
  'WIDMER': 'Switzerland',
  'ELVEDI': 'Switzerland',
  'AKANJI': 'Switzerland',
  'ZAKARIA': 'Switzerland',
  'EMBOLO': 'Switzerland',
  'FREULER': 'Switzerland',
  'MANZAMBI': 'Switzerland',
  'XHAKA': 'Switzerland',
  'NDOYE': 'Switzerland',
  'MVOGO': 'Switzerland',
  'RODRÍGUEZ': 'Switzerland',
  'JASHARI': 'Switzerland',
  'SOW': 'Switzerland',
  'FASSNACHT': 'Switzerland',
  'VARGAS': 'Switzerland',
  'COMERT': 'Switzerland',
  'OKAFOR': 'Switzerland',
  'AEBISCHER': 'Switzerland',
  'KELLER': 'Switzerland',
  'RIEDER': 'Switzerland',
  'AMDOUNI': 'Switzerland',
  'AMENDA': 'Switzerland',
  'JAQUEZ': 'Switzerland',
  'ITTEN': 'Switzerland',
  // Tunisia
  'CHAMAKH': 'Tunisia',
  'ABDI': 'Tunisia',
  'TALBI': 'Tunisia',
  'REKIK': 'Tunisia',
  'AROUS': 'Tunisia',
  'BRONN': 'Tunisia',
  'ACHOURI': 'Tunisia',
  'SAAD': 'Tunisia',
  'MASTOURI': 'Tunisia',
  'MEJBRI': 'Tunisia',
  'GHARBI': 'Tunisia',
  'BEN OUANES': 'Tunisia',
  'KHEDIRA': 'Tunisia',
  'AYARI': 'Tunisia',
  'BELHADJ MAHMOUD': 'Tunisia',
  'DAHMEN': 'Tunisia',
  'SKHIRI': 'Tunisia',
  'ELLOUMI': 'Tunisia',
  'CHAOUAT': 'Tunisia',
  'VALERY': 'Tunisia',
  'BEN HMIDA': 'Tunisia',
  'BEN HSAN': 'Tunisia',
  'NEFFATI': 'Tunisia',
  'CHIKHAOUI': 'Tunisia',
  'SLIMANE': 'Tunisia',
  'TOUNEKTI': 'Tunisia',
  // Turkey
  'MERT': 'Turkey',
  'ZEKI ÇELIK': 'Turkey',
  'DEMIRAL': 'Turkey',
  'ÇAĞLAR': 'Turkey',
  'OZCAN': 'Turkey',
  'ORKUN KÖKÇÜ': 'Turkey',
  'AKTÜRKOĞLU': 'Turkey',
  'ARDA GÜLER': 'Turkey',
  'DENIZ GÜL': 'Turkey',
  'ÇALHANOĞLU': 'Turkey',
  'YILDIZ': 'Turkey',
  'ALTAY': 'Turkey',
  'EREN ELMALI': 'Turkey',
  'ABDÜLKERIM': 'Turkey',
  'OZAN KABAK': 'Turkey',
  'ISMAIL': 'Turkey',
  'KAHVECI': 'Turkey',
  'MERT MULDUR': 'Turkey',
  'YUNUS': 'Turkey',
  'F. KADIOĞLU': 'Turkey',
  'BARIŞ': 'Turkey',
  'KAAN': 'Turkey',
  'UGURCAN': 'Turkey',
  'OGUZ': 'Turkey',
  'SAMET AKAYDIN': 'Turkey',
  'CAN UZUN': 'Turkey',
  // USA
  'TURNER': 'USA',
  'DEST': 'USA',
  'RICHARDS': 'USA',
  'ADAMS': 'USA',
  'A. ROBINSON': 'USA',
  'TRUSTY': 'USA',
  'REYNA': 'USA',
  'MCKENNIE': 'USA',
  'PEPI': 'USA',
  'PULISIC': 'USA',
  'AARONSON': 'USA',
  'M. ROBINSON': 'USA',
  'REAM': 'USA',
  'BERHALTER': 'USA',
  'ROLDAN': 'USA',
  'FREEMAN': 'USA',
  'TILLMAN': 'USA',
  'ARFSTEN': 'USA',
  'WRIGHT': 'USA',
  'BALOGUN': 'USA',
  'WEAH': 'USA',
  'MCKENZIE': 'USA',
  'SCALLY': 'USA',
  'FREESE': 'USA',
  'BRADY': 'USA',
  'ZENDEJAS': 'USA',
  // Uruguay
  'S. ROCHET': 'Uruguay',
  'J.M. GIMÉNEZ': 'Uruguay',
  'S. CÁCERES': 'Uruguay',
  'R. ARAUJO': 'Uruguay',
  'M. UGARTE': 'Uruguay',
